services:
  fazb-app:
    image: node-starter:v1
    container_name: fazb-app
    networks:
      - fazb-net
    ports:
      - "3000:3000"
    volumes:
      - /home/alejo/dev/fazb/fazb_app/:/app/
      - /home/alejo/dev/fazb/fazb_app/node_modules/:/app/node_modules/
      - /home/alejo/dev/fazb/fazb_app/.next:/app/.next
    stdin_open: true
    tty: true
    # entrypoint: ["sh"]
# docker exec -it fazb-app sh
  db-fazb:
    image: postgres:16.8-alpine
    container_name: db-fazb
    networks:
      - fazb-net
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ""
      POSTGRES_USER: ""
      POSTGRES_PASSWORD: ""
    volumes:
      - /home/alejo/dev/fazb/fazb_app/db/data:/var/lib/postgresql/data


networks:
  fazb-net:
    driver: bridge
