services:
    fazb-app:
        image: node-starter:v1
        container_name: fazb-app
        networks:
            - fazb-net
        ports:
            - "3000:3000"
            - "5555:5555"
        volumes:
            - /home/alejo/dev/fazb/fazb_app/:/app/
        stdin_open: true
        tty: true
        environment:
            - CHOKIDAR_USEPOLLING=true
        # entrypoint: ["sh"]
    # docker exec -it fazb-app sh
    db-fazb:
        image: postgres:16.8-alpine
        container_name: db-fazb
        networks:
            - fazb-net
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB:
            POSTGRES_USER:
            POSTGRES_PASSWORD:
        volumes:
            - /home/alejo/dev/fazb/fazb_app/db/data:/var/lib/postgresql/data

networks:
    fazb-net:
        driver: bridge
