version: "3.8"

services:
  app:
    image: clonit/fazb-app:v1.2.4
    user: "1002:1002"
    networks:
      - app-net
    ports:
      - "3000:3000"
    env_file:
      - .env
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      update_config:
        parallelism: 1
        order: start-first
        delay: 15s
      restart_policy:
        condition: on-failure
    volumes:
      - /home/deploy/sites/fazb_app/public_data:/app/public_data

  db:
    image: postgres:16.8-alpine
    networks:
      - app-net
    env_file:
      - .env
    deploy:
      placement:
        constraints: [node.role == manager]
    volumes:
      - /home/deploy/sites/fazb_app/data:/var/lib/postgresql/data
      - /home/deploy/sites/fazb_app/db_dumps:/app/db_dumps
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  app-net:
    driver: overlay
    attachable: true
