services:
    volume-init:
        image: busybox
        command: ["sh", "-c", "chown -R 1001:1001 /public_data"]
        volumes:
            - public_data:/public_data
        networks:
            - app-net
        deploy:
            restart_policy:
                condition: none
            placement:
                constraints:
                    - node.role == manager

    app:
        depends_on:
            - db
        image: clonit/fazb-app:v1.0.1
        user: "1001:1001"
        networks:
            - app-net
        # ports:
        #     - "3000:3000"
        deploy:
            mode: replicated
            replicas: 1
            update_config:
                parallelism: 1
                delay: 15s
                failure_action: rollback
            rollback_config:
                parallelism: 1
                delay: 5s
                failure_action: continue
            placement:
                constraints:
                    - node.role == manager
            restart_policy:
                condition: any
                delay: 10s
                max_attempts: 5
                window: 30s
        volumes:
            - public_data:/public_data
        environment:
            - DATABASE_URL=
            - JWT_COOKIE=ST
            - JWT_DURATION=86400000
            - JWT_SECRET=
            - SYS_ADMIN_EMAIL=
            - SYS_ADMIN_PASSWORD=
            - ADMIN_MAIL_VERIF=contact.learnrhino@gmail.com
            - ADMIN_MAIL_VERIF_PASSWORD=
            - NEXT_PUBLIC_RECAPTCHA_SITE_KEY=6Lcw12IrAAAAAEnp28IOgZq_01u_xXCn32tB56xe
            - RECAPTCHA_SECRET_KEY=
        # secrets:
        #     - database_url
        #     - jwt_secret
        #     - sys_admin_email
        #     - sys_admin_password
        #     - admin_mail_verif_password
        #     - recaptcha_secret_key

    db:
        image: postgres:16.8-alpine
        networks:
            - app-net
        # ports:
        #     - 5432:5432
        deploy:
            placement:
                constraints:
                    - node.role == manager
            restart_policy:
                condition: any
                delay: 10s
                max_attempts: 3
                window: 30s
        volumes:
            - data:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=
            - POSTGRES_USER=
            - POSTGRES_PASSWORD=
        # secrets:
        #     - postgres_db
        #     - postgres_user
        #     - postgres_password

    nginx:
        depends_on:
            - app
        image: nginx:1.29.0
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ../configs/nginx.conf:/etc/nginx/nginx.conf:ro
        networks:
            - app-net
        deploy:
            placement:
                constraints:
                    - node.role == manager
networks:
    app-net:

volumes:
    data:
    public_data:
        # driver: local
        # driver_opts:
        #     type: "nfs"
        #     o: "addr=5.161.222.224,rw"
        #     device: ":/srv/nfs/fazb_public_data"
# secrets:
#     database_url:
#         external: true
#     jwt_secret:
#         external: true
#     sys_admin_email:
#         external: true
#     sys_admin_password:
#         external: true
#     admin_mail_verif_password:
#         external: true
#     recaptcha_secret_key:
#         external: true
#     postgres_db:
#         external: true
#     postgres_user:
#         external: true
#     postgres_password:
#         external: true
