services:
    nginx:
        image: nginx:1.29.0
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./configs/nginx.conf:/etc/nginx/nginx.conf:ro
        networks:
            - fazb-net
        deploy:
            placement:
                constraints:
                    - node.role == manager
networks:
    fazb-net:
        external: true
